/*
 * Copyright 2026 Urs Wolfer
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.urswolfer.intellij.plugin.gerrit.ui;

import com.google.gerrit.extensions.client.ChangeStatus;
import com.google.gerrit.extensions.common.AccountInfo;
import com.google.gerrit.extensions.common.ApprovalInfo;
import com.google.gerrit.extensions.common.ChangeInfo;
import com.google.gerrit.extensions.common.ChangeMessageInfo;
import com.google.gerrit.extensions.common.LabelInfo;
import org.junit.Assert;
import org.testng.annotations.Test;

import java.sql.Timestamp;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class GerritChangeDetailsPanelTest {

    private long time;

    @Test
    public void testVoterOnAnyLabelHasAVote() {
        Map<String, LabelInfo> labels = new LinkedHashMap<>();
        labels.put("Code-Review", label(approval(1, "Rita", 1), approval(2, "bot", 0), approval(3, "Carl", 0)));
        labels.put("Verified", label(approval(1, "Rita", 0), approval(2, "bot", 1), approval(3, "Carl", null)));

        Assert.assertEquals(List.of("Carl"), names(GerritChangeDetailsPanel.getReviewersWithoutVote(
            List.of(account(1, "Rita"), account(2, "bot"), account(3, "Carl")), labels)));
    }

    @Test
    public void testReviewerMissingFromLabels() {
        Map<String, LabelInfo> labels = new LinkedHashMap<>();
        labels.put("Code-Review", label(approval(1, "Rita", 1)));
        labels.put("Verified", new LabelInfo());

        Assert.assertEquals(List.of("Carl"), names(GerritChangeDetailsPanel.getReviewersWithoutVote(
            List.of(account(1, "Rita"), account(3, "Carl")), labels)));
    }

    @Test
    public void testReviewersFromLabelsWithoutReviewerList() {
        Map<String, LabelInfo> labels = new LinkedHashMap<>();
        labels.put("Code-Review", label(approval(1, "Rita", 1), approval(2, "bot", 0), approval(3, "Carl", 0)));
        labels.put("Verified", label(approval(1, "Rita", 0), approval(2, "bot", 1), approval(3, "Carl", 0)));

        Assert.assertEquals(List.of("Carl"), names(GerritChangeDetailsPanel.getReviewersWithoutVote(null, labels)));
    }

    @Test
    public void testAccountNameIsEscaped() {
        AccountInfo account = new AccountInfo("R&D <bot>", null);

        Assert.assertEquals("R&amp;D &lt;bot&gt;", GerritChangeDetailsPanel.accountName(account));
    }

    @Test
    public void testAccountNameWithoutFullName() {
        AccountInfo account = new AccountInfo(" ", null);
        account._accountId = 1000005;
        account.username = "ci-bot";

        Assert.assertEquals("ci-bot", GerritChangeDetailsPanel.accountName(account));
    }

    @Test
    public void testStatusOfWorkInProgress() {
        Assert.assertEquals("NEW, WIP", GerritChangeDetailsPanel.status(change(ChangeStatus.NEW, true)));
    }

    @Test
    public void testStatusOfAbandonedWorkInProgress() {
        Assert.assertEquals("ABANDONED", GerritChangeDetailsPanel.status(change(ChangeStatus.ABANDONED, true)));
    }

    @Test
    public void testStatusOfReadyChange() {
        Assert.assertEquals("NEW", GerritChangeDetailsPanel.status(change(ChangeStatus.NEW, null)));
    }

    @Test
    public void testAutogeneratedMessagesOfEarlierPatchSetsAreLeftOut() {
        ChangeMessageInfo uploaded1 = message("1", "autogenerated:gerrit:newPatchSet", 1);
        ChangeMessageInfo ci1 = message("2", "autogenerated:ci", 1);
        ChangeMessageInfo review = message("3", null, 1);
        ChangeMessageInfo otherTag = message("4", "ci", 1);
        ChangeMessageInfo uploaded2 = message("5", "autogenerated:gerrit:newPatchSet", 2);
        ChangeMessageInfo ci2Started = message("6", "autogenerated:ci", 2);
        ChangeMessageInfo ci2Done = message("7", "autogenerated:ci", 2);

        Assert.assertEquals(List.of(review, otherTag, uploaded2, ci2Started, ci2Done),
            GerritChangeDetailsPanel.withoutAutogenerated(
                List.of(uploaded1, ci1, review, otherTag, uploaded2, ci2Started, ci2Done)));
    }

    @Test
    public void testAutogeneratedMessageWithoutPatchSetIsLeftOutForALaterOne() {
        ChangeMessageInfo withoutPatchSet = message("1", "autogenerated:ci", null);
        ChangeMessageInfo later = message("2", "autogenerated:ci", 1);

        Assert.assertEquals(List.of(later),
            GerritChangeDetailsPanel.withoutAutogenerated(List.of(withoutPatchSet, later)));
    }

    @Test
    public void testAutogeneratedMessageWithoutPatchSetBelongsToThePatchSetBefore() {
        ChangeMessageInfo ci1 = message("1", "autogenerated:ci", 1);
        ChangeMessageInfo uploaded2 = message("2", "autogenerated:gerrit:newPatchSet", 2);
        ChangeMessageInfo withoutPatchSet = message("3", "autogenerated:ci", null);

        Assert.assertEquals(List.of(uploaded2, withoutPatchSet),
            GerritChangeDetailsPanel.withoutAutogenerated(List.of(ci1, uploaded2, withoutPatchSet)));
    }

    @Test
    public void testAutogeneratedTagsAreGroupedAsInGerritsWebUi() {
        ChangeMessageInfo wipUploaded1 = message("1", "autogenerated:gerrit:newWipPatchSet", 1);
        ChangeMessageInfo ciRun1 = message("2", "autogenerated:ci~run1", 1);
        ChangeMessageInfo uploaded2 = message("3", "autogenerated:gerrit:newPatchSet", 2);
        ChangeMessageInfo ciRun2 = message("4", "autogenerated:ci~run2", 2);

        Assert.assertEquals(List.of(uploaded2, ciRun2),
            GerritChangeDetailsPanel.withoutAutogenerated(List.of(wipUploaded1, ciRun1, uploaded2, ciRun2)));
    }

    @Test
    public void testUploadWhichOutdatesVotesIsAGroupOfItsOwn() {
        ChangeMessageInfo outdating = message("1", "autogenerated:gerrit:newPatchSet", 1);
        outdating.message = "Uploaded patch set 1.\n\nOutdated Votes:\nCode-Review+1 by Someone";
        ChangeMessageInfo setPrivate = message("2", "autogenerated:gerrit:setPrivate", 1);
        ChangeMessageInfo uploaded2 = message("3", "autogenerated:gerrit:newPatchSet", 2);
        ChangeMessageInfo unsetPrivate = message("4", "autogenerated:gerrit:unsetPrivate", 2);

        Assert.assertEquals(List.of(outdating, uploaded2, unsetPrivate),
            GerritChangeDetailsPanel.withoutAutogenerated(List.of(outdating, setPrivate, uploaded2, unsetPrivate)));
    }

    @Test
    public void testWorkInProgressAndReadyForReviewAreOneGroup() {
        ChangeMessageInfo setReady = message("1", "autogenerated:gerrit:setReadyForReview", 1);
        ChangeMessageInfo setWip = message("2", "autogenerated:gerrit:setWorkInProgress", 2);

        Assert.assertEquals(List.of(setWip),
            GerritChangeDetailsPanel.withoutAutogenerated(List.of(setReady, setWip)));
    }

    private static ChangeMessageInfo message(String id, String tag, Integer revisionNumber) {
        ChangeMessageInfo message = new ChangeMessageInfo(id);
        message.tag = tag;
        message._revisionNumber = revisionNumber;
        return message;
    }

    private static ChangeInfo change(ChangeStatus status, Boolean workInProgress) {
        ChangeInfo change = new ChangeInfo();
        change.status = status;
        change.workInProgress = workInProgress;
        return change;
    }

    private static LabelInfo label(ApprovalInfo... approvals) {
        LabelInfo label = new LabelInfo();
        label.all = List.of(approvals);
        return label;
    }

    private static AccountInfo account(int accountId, String name) {
        AccountInfo account = new AccountInfo(accountId);
        account.name = name;
        return account;
    }

    private ApprovalInfo approval(int accountId, String name, Integer value) {
        ApprovalInfo approval = new ApprovalInfo(accountId);
        approval.name = name;
        approval.value = value;
        // differs per label, as it does in Gerrit's answer
        approval.date = new Timestamp(++time);
        return approval;
    }

    private static List<String> names(List<AccountInfo> accounts) {
        return accounts.stream().map(account -> account.name).collect(Collectors.toList());
    }
}
